### ISSUE TITLE
Multiple keys for different cognitive services

### ISSUE THREAD

**Issue by antonio8101** [artiso-solutions/CoVoX#10]
Apparently it seems customers have to create different keys for each cognitive services.
Maybe there's an overall key that allows to use them all with a key, but apparently not all the service are included in that "schema".

**Comment by antonio8101** [comment]
It is possible to run multiple Cognitive Services with the same key (without having to create a key for each services).

The steps to the creating of multi-service key are the following:
- Create a `Resource` from the main menu.
- Select `Cognitive Services` from the  list of market place services available.

The `Key` available are tested for the usage of the following services:
- SpeechToText
- Translate

**Comment by tommasobertoni** [comment]
Could you test with all of the mentioned services?
- [Speech to Text](https://azure.microsoft.com/en-us/services/cognitive-services/speech-to-text/)
- [Translator](https://azure.microsoft.com/en-us/services/cognitive-services/translator/)
- [Speech Translation](https://azure.microsoft.com/en-us/services/cognitive-services/speech-translation/)
- [Language Understanding](https://azure.microsoft.com/en-us/services/cognitive-services/language-understanding-intelligent-service/)
- [Text Analytics](https://azure.microsoft.com/en-gb/services/cognitive-services/text-analytics/)
- (others that I may have missed)

**Comment by antonio8101** [comment]
The key for multiple services doesn't allow to use the free-tier pricing schema

**Comment by antonio8101** [comment]
A unique key to use all the Cognitive Services with one key can be done by creating a `Resource` in the Azure.

- Vision 
- Language
- Search
- Speech

**Comment by antonio8101** [comment]
> A unique key to use multiple Cognitive Services with one key can be done by creating a `Resource` in the Azure.
> The unique key allows to use all the service in service area:
> 
> * Vision
> * Language (even language understanding)
> * Search
> * Speech



> Could you test with all of the mentioned services?
> 
> * [Speech to Text](https://azure.microsoft.com/en-us/services/cognitive-services/speech-to-text/) - OK
> * [Translator](https://azure.microsoft.com/en-us/services/cognitive-services/translator/) - OK
> * [Speech Translation](https://azure.microsoft.com/en-us/services/cognitive-services/speech-translation/) - TODO
> * [Language Understanding](https://azure.microsoft.com/en-us/services/cognitive-services/language-understanding-intelligent-service/) - KO (different keys)
> * [Text Analytics](https://azure.microsoft.com/en-gb/services/cognitive-services/text-analytics/) - TODO
> * (others that I may have missed)
