### ISSUE TITLE
Language filter using confidence score

### ISSUE THREAD

**Issue by kczornik** [artiso-solutions/CoVoX#12]
Test if it is possible to filter out translations by the confidence score of the translation received by the API when no "from" language is given

**Comment by kczornik** [comment]
It doesn't look like it is possible to filter out the results this way

**Comment by tommasobertoni** [comment]
We should try the [pronunciation configuration](https://docs.microsoft.com/en-us/azure/cognitive-services/speech-service/how-to-pronunciation-assessment?pivots=programming-language-csharp#pronunciation-assessment-configuration-parameters).
```csharp
var pronunciationAssessmentConfig = new PronunciationAssessmentConfig(
    "reference text", GradingSystem.HundredMark, Granularity.Phoneme);

using (var recognizer = new SpeechRecognizer(
    speechConfig,
    audioConfig))
{
    // apply the pronunciation assessment configuration to the speech recognizer
    pronunciationAssessmentConfig.ApplyTo(recognizer);
    var speechRecognitionResult = await recognizer.RecognizeOnceAsync();
    var pronunciationAssessmentResult =
        PronunciationAssessmentResult.FromResult(speechRecognitionResult);
    var pronunciationScore = pronunciationAssessmentResult.PronunciationScore;
}
```

> `AccuracyScore`: Pronunciation accuracy of the speech. Accuracy indicates how closely the phonemes match a native speaker's pronunciation. Word and full text level accuracy score is aggregated from phoneme level accuracy score.

**Comment by kczornik** [comment]
ReferenceText ist a required field for the PronunciationAssessmentConfig, but in our case we don't know the expected text?
